create table
    "public"."order" (
        "id" bigint generated by default as identity not null,
        "user_id" bigint not null,
        "order" json not null,
        "created_at" timestamp
        with
            time zone not null default now ()
    );

alter table "public"."order" enable row level security;

CREATE UNIQUE INDEX order_pkey ON public."order" USING btree (id);

alter table "public"."order" add constraint "order_pkey" PRIMARY KEY using index "order_pkey";

grant delete on table "public"."order" to "anon";

grant insert on table "public"."order" to "anon";

grant references on table "public"."order" to "anon";

grant
select
    on table "public"."order" to "anon";

grant trigger on table "public"."order" to "anon";

grant truncate on table "public"."order" to "anon";

grant
update on table "public"."order" to "anon";

grant delete on table "public"."order" to "authenticated";

grant insert on table "public"."order" to "authenticated";

grant references on table "public"."order" to "authenticated";

grant
select
    on table "public"."order" to "authenticated";

grant trigger on table "public"."order" to "authenticated";

grant truncate on table "public"."order" to "authenticated";

grant
update on table "public"."order" to "authenticated";

grant delete on table "public"."order" to "service_role";

grant insert on table "public"."order" to "service_role";

grant references on table "public"."order" to "service_role";

grant
select
    on table "public"."order" to "service_role";

grant trigger on table "public"."order" to "service_role";

grant truncate on table "public"."order" to "service_role";

grant
update on table "public"."order" to "service_role";

create policy "allow anon user insert" on "public"."order" as permissive for insert to anon
with
    check (true);
